name: build & deploy book

on:
  push:
    branches: [main_zh]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - name: Build the Book
        run: mdbook build

      - run: cp ./robots.txt ./book/

      # - name: Deploy to Github pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     deploy_key: ${{ secrets.BOOK_DEPLOY_KEY }}
      #     publish_branch: main_zh
      #     publish_dir: ./book
      #
      #
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: zh
          build_dir: ./book
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
